version: "2.4"
services:

  # Web server instance (the only external facing service)
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "siteconf:/etc/nginx/conf.d:ro"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "acme-challenge:/var/www/certbot:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  openldap:
    image: "osixia/openldap:stable"
    volumes:
      - "ldap:/var/lib/ldap"
      - "slapd.d:/etc/ldap/slapd.d"

  ldap-auth:
    image: "linuxserver/ldap-auth:version-3.3.1"

  apps:
    image: "edtwardy/apps:latest"
    volumes:
      - "apps-database:/data/database"
      - "apps-media:/data/media"
      - "apps-static:/data/static:ro"
    environment:
      - DJANGO_HOSTNAME=edtwardy.hopto.org
      - SCRIPT_NAME=/apps

  # TODO: Conan Server
  # TODO: PyPI Server
  # TODO: Mini-Dinstall

volumes:
  siteconf:
    external: true
  letsencrypt:
    external: true
  acme-challenge: # Use default volume
  ldap:
    external: true
  slapd.d:
    external: true
  apps-database:
    external: true
  apps-media:
    external: true
  apps-static:
    external: true
