version: "2.4"
services:

  # Web server instance (the only external facing service)
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "siteconf:/etc/nginx/conf.d:ro"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "acme-challenge:/var/www/certbot:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  # TODO: openldap:
  #   image: osixia/openldap:stable
  # TODO: ldap-auth:
  #   image: linuxserver/ldap-auth:version-3.3.1
  # TODO: Django project as packaged pip application

# TODO: persist container logs to volume
#   certbot:/var/log/letsencrypt.log
#   nginx:/var/log/nginx/{access,error}.log
volumes:
  siteconf:
    external: true
  letsencrypt:
    external: true
  acme-challenge: # No content in this by default.
