version: "2.4"
services:

  # Web server instance (the only external facing service)
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "siteconf:/etc/nginx/conf.d:ro"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "acme-challenge:/var/www/certbot:ro"
      - "apps-media:/var/www/media:ro"
      - "apps-static:/var/www/static:ro"
      - "repository:/var/www/repository:ro"
      - "blog:/var/www/blog:ro"
      - "/mnt/Serve/yocto/sstate-cache:/data/yocto/sstate-cache:ro"
      - "/mnt/Serve/yocto/esdk:/data/yocto/esdk:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  openldap:
    image: "osixia/openldap:stable"
    volumes:
      - "ldap:/var/lib/ldap"
      - "slapd.d:/etc/ldap/slapd.d"

  apps:
    image: "edtwardy/apps:latest"
    volumes:
      - "apps-database:/data/database"
      - "apps-media:/data/media"
      - "apps-static:/data/static:ro"
      - "apps-secrets:/data/secrets:ro"
    environment:
      - DJANGO_HOSTNAME=www.twardyece.com:twardyece.com
      - SCRIPT_NAME=/apps

  jenkins-controller:
    image: "jenkins/jenkins:lts"
    volumes:
      - "jenkins:/var/jenkins_home"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

  jenkins-agent:
    image: "edtwardy/jenkins-agent:latest"
    init: true
    depends_on:
      - jenkins-controller
    volumes:
      - "repository:/home/jenkins/repository"
      - "blog:/home/jenkins/blog"
      - "agent-secret:/secrets:ro"
    environment:
      - REPOSITORY_MOUNT=/home/jenkins/repository

  # TODO: Conan Server
  # TODO: PyPI Server
  # TODO: Mini-Dinstall

volumes:
  siteconf:
    external: true
  letsencrypt:
    external: true
  acme-challenge: # Use default volume
  ldap:
    external: true
  slapd.d:
    external: true
  apps-database:
    external: true
  apps-media:
    external: true
  apps-static:
    external: true
  repository: # Use default volume
  jenkins:
    external: true
  agent-secret:
    external: true
  apps-secrets:
    external: true
  blog: # Use default volume
